name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy To Firebase
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@masters
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WINE_LOTTERY_DEV }}
