name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install
      run: npm ci
    - name: Lint
      uses: wearerequired/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        stylelint: true
        stylelint_extensions: 'scss'
        eslint: true
        eslint_extensions: 'ts,html'
    - name: Build & Compare sizes
      uses: preactjs/compressed-size-action@v2
      with:
        build-script: "build-ci"
        pattern: "./dist/web/*.{js,css,html}"
        strip-hash: "\\b\\w{5}\\."
      env:
        CI: true
#  storybook:
#    name: Build Storybook
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [16.x]
#    steps:
#      - uses: actions/checkout@v1
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: NPM install
#        run: npm ci
#      - name: Build Storybook
#        run: npm run build-storybook
