name: Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-head:
    name: 'Build Head'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Lint
      uses: wearerequired/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        stylelint: true
        stylelint_extensions: 'scss'
        eslint: true
        eslint_extensions: 'ts,html'
    - name: Build
      run: npm run build -- --stats-json
      env:
        CI: true
    - name: Upload stats.json
      uses: actions/upload-artifact@v1
      with:
        name: head-stats
        path: ./dist/web/stats.json
  build-base:
    name: 'Build Base'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
      with:
        ## Here we do not checkout the current branch, but we checkout the base branch.
        ref: ${{ github.base_ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build -- --stats-json
      env:
        CI: true
    - name: Upload stats.json
      uses: actions/upload-artifact@v1
      with:
        name: base-stats
        path: ./dist/web/stats.json
  compare:
    name: 'Compare base & head bundle sizes'
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    steps:
    - uses: actions/checkout@v1
    - name: Download base artifact
      uses: actions/download-artifact@v1
      with:
        name: base-stats
    - name: Download head artifact
      uses: actions/download-artifact@v1
      with:
        name: head-stats
    - name: Diff between base & head
      uses: chronotruck/webpack-stats-diff-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base_stats_path: ./base-stats/stats.json
        head_stats_path: ./head-stats/stats.json
#  storybook:
#    name: Build Storybook
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [16.x]
#    steps:
#      - uses: actions/checkout@v1
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: NPM install
#        run: npm ci
#      - name: Build Storybook
#        run: npm run build-storybook
